import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import SmallCard from '../components/SmallCard/SmallCard'
import Htag from '../components/Header/Htag'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SmallCard amount={1478286} percent='4.07' renderCase='visits'>
          TEST
        </SmallCard>
        <Htag tag={'h1'}> 
          Header
        </Htag>
        <Htag tag={'h2'}> 
          Header
        </Htag>
        <Htag tag={'h3'}> 
          Header
        </Htag>
        <div>
          MAIN
        </div>
        <div>
          FOOTER
        </div>
      </main>

    </div>
  )
}

export default Home
