import type { NextPage } from "next";
import Head from "next/head";
import SmallCard from "../components/SmallCard/SmallCard";
import Htag from "../components/Header/Htag";
import ChartIcon from "../helpers/cardIcons/icons/blank.svg";
import TrendUp from "../helpers/trendsIcons/icons/trendUp.svg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <SmallCard
          TrendIcon={TrendUp}
          Icon={ChartIcon}
          amount={1478286}
          percent="4.07"
          renderCase="visits"
        >
          TEST
        </SmallCard>
        <Htag tag={"h1"}>Header</Htag>
        <Htag tag={"h2"}>Header</Htag>
        <Htag tag={"h3"}>Header</Htag>
        <div>MAIN</div>
        <div>FOOTER</div>
      </div>
    </div>
  );
};

export default Home;
